name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket-name:
        description: 'S3 bucket name (must be globally unique)'
        required: true
      region:
        description: 'AWS region (default: us-east-1)'
        required: false
        default: 'us-east-1'

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Create S3 bucket if not exists
        env:
          BUCKET: ${{ github.event.inputs.bucket-name }}
          REGION: ${{ github.event.inputs.region }}
        run: |
          set -euo pipefail
          echo "Bucket: $BUCKET"
          echo "Region: ${REGION:-us-east-1}"

          # Check if bucket exists (accessible)
          if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
            echo "✅ Bucket $BUCKET already exists and is accessible."
            exit 0
          fi

          # Create bucket (handle us-east-1 special case)
          if [ "${REGION:-us-east-1}" = "us-east-1" ]; then
            echo "Creating bucket in us-east-1..."
            aws s3api create-bucket --bucket "$BUCKET"
          else
            echo "Creating bucket in region $REGION..."
            aws s3api create-bucket \
              --bucket "$BUCKET" \
              --create-bucket-configuration LocationConstraint="$REGION"
          fi

          aws s3api wait bucket-exists --bucket "$BUCKET"

          # Block public access
          aws s3api put-public-access-block \
            --bucket "$BUCKET" \
            --public-access-block-configuration '{
              "BlockPublicAcls": true,
              "IgnorePublicAcls": true,
              "BlockPublicPolicy": true,
              "RestrictPublicBuckets": true
            }'

          # Enable default SSE (AES256)
          aws s3api put-bucket-encryption \
            --bucket "$BUCKET" \
            --server-side-encryption-configuration '{
              "Rules":[
                {"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}
              ]
            }'

          echo "✅ Bucket $BUCKET created and configured successfully."
